CMakeLists.txt
samples/saveframe/CMakeLists.txt
samples/saveframe/source/saveframe.c

This commit add a sample that supports capture a raw frame and save to file system.

samples: add save frame sample

---

samples/saveframe/source/saveframe.c
source/T31/T31VideoCapturer.c

t31 video capturer: add support for 360p

---

CMakeLists.txt
README.md
samples/saveframe/source/saveframe.c
source/T31/T31VideoCapturer.c

save frame sample: introduce NV12_TO_RGB24

save frame sample: introduce NV12_TO_RGB24

---

.github/workflows/main.yml
README.md

Create github actions

---

source/T31/T31AudioPlayer.c

audio player: fix pointer warning

---

.github/workflows/main.yml

workflow: add build test for ingenic 5.4.0

---

README.md

readme: add guides for using ak/sk as credentials in webrtc

---

samples/webrtc/CMakeLists.txt
samples/webrtc/source/Common.c
samples/webrtc/source/kvsWebRTCClientMaster.c

update webrtc sample to 1.7.0

---

.github/workflows/main.yml
.gitignore
3rdparty/README.md
CMakeLists.txt

naming rule: use uppercase in 3rdparty path

---

.github/workflows/cmake.yml
.github/workflows/ecr-prepare.yml

workflows: separate ecr prepare and cmake build

---

.github/workflows/main.yml

Fix workflow secrets issue

---

CMake/T31.cmake
CMakeLists.txt
README.md

Move board specific parts into standalone cmake

---

.github/workflows/develop.yml
.github/workflows/main.yml

workflow: add event trigger for pr and push

---

samples/kvs/source/kvsappcli.c
samples/kvs/source/sample_config.h
samples/webrtc/source/kvsWebRTCClientMaster.c

sample: allow audio capturer/player init failed

---

samples/webrtc/source/Common.c

webrtc: disable twcc to save ram

---

source/V4L2/V4L2Common.h
source/V4L2/V4L2VideoCapturer.c

v4l2: add implementation for video capturer

---

source/T31/T31AudioCapturer.c
source/T31/T31VideoCapturer.c
source/V4L2/V4L2Common.h
source/V4L2/V4L2VideoCapturer.c

v4l2/t31: disallow change format when stream is on

---

3rdparty/V4L2/V4L2Port.c
3rdparty/V4L2/V4L2Port.h
CMake/V4L2.cmake
samples/kvs/source/kvsappcli.c
samples/saveframe/source/saveframe.c
source/V4L2/V4L2VideoCapturer.c

V4l2 timestamp fix

---

CMake/FILE.cmake
CMakeLists.txt
source/FILE/FILEAudioCapturer.c
source/FILE/FILECommon.h

file capturer: allow user to specify sample frames path

---

samples/webrtc/CMakeLists.txt

Fix chrome 98

---

samples/webrtc/CMakeLists.txt
source/FILE/FILECommon.h

webrtc: update webrtc sdk to fix offer handle issue on chrome 98

---

3rdparty/README.md
samples/kvs/source/kvsappcli.c

Kvs sample gracefully exit

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build-issue.md
.github/ISSUE_TEMPLATE/question.md
samples/kvs/CMakeLists.txt
samples/kvs/source/option_configuration.c
samples/kvs/source/option_configuration.h
samples/kvs/source/sample_config.h
samples/webrtc/CMakeLists.txt

webrtc: update webrtc sdk version to v1.7.2
producer: update producer sdk version to v1.0.0

SDK update

---

.github/workflows/main.yml
.gitignore

add workflow for FH8626V100

---

samples/webrtc/source/Common.c

This PR will merge amazon-kinesis-video-streams-webrtc-sdk-c/pull/1448 to fix possible deadlock issue in freeSampleStreamingSession

webrtc: merge amazon-kinesis-video-streams-webrtc-sdk-c/pull/1448

---

samples/webrtc/CMakeLists.txt
samples/webrtc/source/Common.c
samples/webrtc/source/kvsWebRTCClientMaster.c

webrtc: upgrade to v1.7.3

---

.github/workflows/develop.yml
.github/workflows/main.yml

This commit allows user to trigger workflow manually

github actions: allow to trigger workflow manually

---

.github/workflows/develop.yml
.github/workflows/main.yml

[github actions: allow to trigger workflow manually](https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/commit/790f586f01c8caf2ccb7074cf415a6ddee69f3e4)

github actions: allow to trigger workflow manually 

---

samples/webrtc/CMakeLists.txt
samples/webrtc/patches/webrtc-patch-manager.sh

webrtc: fix possible patch error when build more than once

webrtc: fix possible patch error when build more than once

---

3rdparty/README.md
README.md

doc: add toc

---

README.md
samples/webrtc/source/kvsWebRTCClientMaster.c

[readme: update supported board table](https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/commit/6c1956adcbadd6b99f4dab3b43bb713d4fd39805)
[webrtc: increase default frame buffer to 256kb](https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/commit/f11c0e221e82eb3ed05cadc97dce523b231fc40c)

Buffer increase

---

3rdparty/README.md
README.md

doc: fix ak3918 title issue

---

CMake/V4L2.cmake

Upgrade V4L2Capturer to master

---

.github/workflows/amlogic-c302.yml
.github/workflows/anyka-ak3918.yml
.github/workflows/fullhan-fh8626v100.yml
.github/workflows/ingenic-t31.yml

workflow: upgrade ecr login

---

.github/workflows/amlogic-c302.yml
.github/workflows/anyka-ak3918.yml
.github/workflows/eeasy-sv82x.yml
.github/workflows/file.yml
.github/workflows/fullhan-fh8626v100.yml
.github/workflows/ingenic-t31.yml
.github/workflows/v4l2.yml

mbedtls is incompatible with gcc-11. We will use gcc-10 in workflow instead.

workflow: use gcc-10 and g++-10 for x64 environment

---

README.md
samples/kvsproducer/CMakeLists.txt

producer: bump to main branch

---

samples/webrtc/source/Common.c
samples/webrtc/source/Samples.h

Introduce DNS resolve bypass feature

---

doc/markdown/memory.md

Add a doc describe how to optimize WebRTC memory footprint.

add WebRTC memory optimize doc

---

source/T31/T31AudioCapturer.c
source/T31/T31VideoCapturer.c

Fix compile error on T31

---

samples/webrtc/CMakeLists.txt

set webrtc sdk to tag v1.8.1

---

README.md
samples/kvsproducer/source/kvsappcli.c
samples/kvsproducer/source/sample_config.h

Support KVS to run using certificate mode through environment variable

---

source/C302/C302AudioCapturer.c
source/C302/C302AudioPlayer.c
source/C302/C302VideoCapturer.c

C302: fix an issue that insufficient buffer might cause segmentation fault

---

samples/webrtc/source/Common.c
samples/webrtc/source/Samples.h
samples/webrtc/source/kvsWebRTCClientMaster.c

webrtc: update to v1.8.1 release

---

3rdparty/GSTREAMER/GSTREAMERGstCmd.h
3rdparty/QCS610/QCS610GstCmd.h

Fixing the frame drop rate issue
